// Generate docs/agent.md from the agent's own definitions (action schemas,
// runner tools, limits and system prompt), so the reference cannot drift
// from the code. tests/agent-docs.test.js fails when the file is stale.
//
//   node scripts/agent-docs.mjs
import { writeFileSync } from 'node:fs';
import CM from '../tests/load.js';

const { AGENT_ACTIONS, RUNNER_TOOLS, LLM_ACTIONS, AGENT_LIMITS, AGENT_SYSTEM_PROMPT, DEFAULT_LLM } = CM;

// One line per argument: name, type, required, description.
function typeOf(s) {
  if (!s) return 'any';
  if (s.enum) return s.enum.map((v) => (v === null ? 'null' : `"${v}"`)).join(' \\| ');
  if (s.type === 'array') return `${typeOf(s.items)}[]`;
  if (s.type === 'object' && s.properties?.x && s.properties?.y && Object.keys(s.properties).length === 2) return '{x, y}';
  if (s.type === 'object' && s.properties) return `{${Object.keys(s.properties).join(', ')}}`;
  let t = s.type || 'any';
  const range = [];
  if (s.minimum !== undefined) range.push(`≥ ${s.minimum}`);
  if (s.exclusiveMinimum !== undefined) range.push(`> ${s.exclusiveMinimum}`);
  if (s.maximum !== undefined) range.push(`≤ ${s.maximum}`);
  if (range.length) t += ` (${range.join(', ')})`;
  return t;
}

const esc = (text) => String(text || '').replaceAll('|', '\\|').replaceAll('\n', ' ');

function argsTable(schema) {
  const props = Object.entries(schema.properties || {});
  if (!props.length) return '_No arguments._\n';
  const req = new Set(schema.required || []);
  return [
    '| Argument | Type | Required | Description |',
    '| --- | --- | --- | --- |',
    ...props.map(([k, s]) => `| \`${k}\` | ${esc(typeOf(s))} | ${req.has(k) ? 'yes' : ''} | ${esc(s.description)} |`),
    '',
  ].join('\n');
}

function section(name, spec, extra = '') {
  return `### \`${name}\`\n\n${esc(spec.description)}${spec.mutates ? ' _Changes the project; undoable._' : ''}${extra}\n\n${argsTable(spec.args)}`;
}

const groups = [
  ['Reading', ['get_state', 'get_results', 'get_questions', 'sample_pixel', 'focus']],
  ['File, tool and page', ['open_url', 'set_tool', 'go_to_page', 'select_panel', 'add_panel', 'rename_panel', 'remove_panel']],
  ['Grid', ['set_grid', 'detect_grid_size', 'set_grid_size', 'set_labels', 'remove_grid']],
  ['Colorbar and matching', ['set_colorbar', 'add_tick', 'set_tick_value', 'remove_tick', 'set_colorbar_scale', 'set_settings']],
  ['ROI regions', ['add_region', 'remove_region', 'set_scale_bar']],
  ['Decisions and review', ['answer_question', 'set_review']],
  ['History and export', ['undo', 'redo', 'export_project']],
];
const listed = new Set(groups.flatMap(([, names]) => names));
const missing = Object.keys(AGENT_ACTIONS).filter((n) => !listed.has(n));
if (missing.length) throw new Error(`Add these actions to a group in scripts/agent-docs.mjs: ${missing.join(', ')}`);

const llmOnly = (n) => (LLM_ACTIONS.includes(n) ? ' _Available to the heatmap agent\'s LLM._' : '');

const md = `<!-- Generated by scripts/agent-docs.mjs from the agent's definitions; do not edit by hand. -->
# Colormeris agent reference

Colormeris can be driven by software agents in two ways:

- **Agent API** (\`window.colormeris\`, [assets/js/agent/api.js](../assets/js/agent/api.js)): typed actions any program can call from the page.
- **Heatmap agent** (the *Agent* card, [assets/js/agent/runner.js](../assets/js/agent/runner.js)): an LLM that calls those actions to calibrate every heatmap on the chosen pages, checking its own work with overlays.

All coordinates are pixels of the panel's page image, the same space as \`project.json\`.

## Agent API

\`\`\`js
const r = await colormeris.run('add_tick', { at: { x: 606, y: 822 }, value: 3 });
// → { ok: true, result: { tickId, t }, state }   or   { ok: false, error }
\`\`\`

- \`colormeris.run(name, args)\` validates \`args\` against the action's JSON Schema, runs the action and never throws. Actions that change the project also return \`state\` (as \`get_state\`). Results may carry \`notes\` when arguments were adjusted.
- Arguments are forgiven in two common cases: optional arguments sent as \`null\` are dropped, and \`add_tick\` given both \`at\` and \`t\` uses \`at\`.
- \`colormeris.batch([{ name, args }, …])\` runs actions in order and stops at the first failure.
- \`colormeris.tools()\` returns every action as \`{ name, description, input_schema }\`, the tool format LLM APIs take.
- \`colormeris.policy.minConfidence\` (default 0.9) is the confidence an \`answer_question\` answer needs to be applied. \`colormeris.log()\` returns the action and decision logs, which project zips store as \`agent/actions.json\` and \`agent/decisions.json\`.

${groups.map(([title, names]) => `## ${title}\n\n${names.map((n) => section(n, AGENT_ACTIONS[n], llmOnly(n))).join('\n')}`).join('\n')}
## Typed questions

\`get_questions\` lists decisions with an \`id\`, \`type\`, \`panelId\`, \`prompt\`, \`evidence\` and an \`answerSchema\`. \`answer_question\` answers one with a \`confidence\` and a \`source\`; answers below the policy confidence are logged but not applied, and the question stays open with the answer attached as \`escalated\`. Answers from \`source: "human"\` always apply.

| Type | Asked when | Answer | Effect when applied |
| --- | --- | --- | --- |
| \`confirm_grid_size\` | the grid size was detected | \`{rows, cols}\` | sets the size |
| \`classify_flagged\` | a cell is far from every colorbar color (3 or fewer such cells) | \`"keep"\` \\| \`"exclude"\` \\| \`"recheck_colorbar"\` | \`exclude\` lists the cell under \`excluded\` in results |
| \`classify_flagged_cells\` | more than 3 flagged cells: one question for all of them | \`"keep_all"\` \\| \`"exclude_all"\` \\| \`"recheck_colorbar"\` | \`exclude_all\` lists them under \`excluded\` |
| \`confirm_tick_order\` | tick values do not change monotonically along the bar | \`"as_placed"\` \\| \`"fix_needed"\` | recorded |
| \`confirm_extraction\` | a panel has values and no review of them | \`"accept"\` \\| \`"reject"\` | sets the panel's review |

### Reviews

A panel's review (\`accepted\` or \`rejected\`, who decided, confidence and a note) is stored on the panel and saved in \`project.json\`. It applies to the values it was made on: once they change, its status becomes \`stale\` and a new \`confirm_extraction\` question opens. A rejected panel has a red dot in the Panels list and stays under *Needs review* until it is accepted or changed.

## Heatmap agent

The *Agent* card runs an LLM (default \`${DEFAULT_LLM}\`; any OpenRouter model with image input and tool calling) through the OpenRouter TypeScript SDK.

1. The LLM sees page images with pixel rulers, finds the heatmaps, and calibrates one panel per heatmap with the actions marked above. It zooms in with \`view_page\` and checks its work with overlays. \`set_colorbar\` snaps the line to the strip's centre and its ends to the first and last colored pixel, and \`add_tick\` snaps to the nearest tick mark (outside the bar or drawn into it), because models read coordinates a few pixels off. \`finish\` is refused while pages of the run are unseen or panels half done, and the first time it is answered with a per-page checklist, so the model does not stop after the first heatmap.
2. Answers below *Min. confidence* go to *Needs review* in the card. There you can answer them, accept, reject or delete a panel, and use *Redo with agent* to have the agent fix a rejected panel with your note.

### Images

Each image shows a region of the page. Image pixel (0, 0) is the region's top-left corner, and the note sent with the image gives the conversion: page x = x0 + image x / scale (same for y). Rulers on the bottom and right edges are labelled in page pixels. (Rulers on the left and top once shifted every placement by the ruler width divided by the zoom.)

### Runner tools

These are handled by the runner itself, in addition to the actions marked above.

${Object.entries(RUNNER_TOOLS).map(([n, t]) => section(n, t)).join('\n')}
### Limits and retries

| Limit | Value |
| --- | --- |
| Attempts of one tool on one panel before it is blocked for that panel | ${AGENT_LIMITS.MAX_ATTEMPTS} |
| Failed tool calls in a row before the run stops | ${AGENT_LIMITS.MAX_ERRORS_IN_A_ROW} |
| Refused \`finish\` calls (pages not viewed, partly calibrated panels, final checklist) before \`finish\` is always accepted | ${AGENT_LIMITS.MAX_FINISH_REFUSALS} |
| Steps (LLM calls) per run | *Max. steps* in the card (default 80) |
| Replies without a tool call before the run ends | 3 |

A failed call's error tells the model which attempt it was and what to do next. Old images are replaced by a note, so that between 3 and 6 of the newest stay in the conversation.

### Prompt caching

Every step resends the system prompt, the tool list and the whole conversation. Each request sets a top-level \`cache_control\` (1-hour lifetime), which makes Anthropic models cache everything up to the last block and move the breakpoint forward as the conversation grows; other providers cache the shared start of the request by themselves. A \`session_id\` per run keeps the requests on the provider that holds the cache (see the [OpenRouter guide](https://openrouter.ai/docs/guides/best-practices/prompt-caching)). Old images are trimmed in steps of four messages instead of one per step, so the start of the request stays the same for several steps in a row. The card shows the share of prompt tokens read from the cache. Anthropic charges 2× the input price for a 1-hour cache write and 0.1× for a read; models below the minimum prompt size (1024 to 4096 tokens, depending on the model) are not cached.

### Key and privacy

The agent uses your own OpenRouter key and sends page images and extracted values to OpenRouter and the model providers you pick. The key stays in memory unless you tick *Remember the key* (then it is kept in this browser's local storage).

To keep the key out of the browser entirely, put \`OPENROUTER_API_KEY=…\` in \`.env\` (ignored by git), run \`npm run proxy\`, and set *API base URL* to \`http://localhost:8787/api/v1\` with the key field empty. The proxy (\`scripts/openrouter-proxy.mjs\`) forwards only OpenRouter API paths, only for pages served from localhost, and adds the key itself. Serve the app with \`npm run serve\`: pages opened from disk are refused by the proxy.

### System prompt

\`\`\`text
${AGENT_SYSTEM_PROMPT}
\`\`\`
`;

export default md;

if (import.meta.url === `file://${process.argv[1]}`) {
  writeFileSync(new URL('../docs/agent.md', import.meta.url), md);
  console.log('wrote docs/agent.md');
}
